name = "my-note-worker"
main = "src/index.js"
compatibility_date = "2025-11-27"

# [vars] တွင် Admin Secret ကို ထည့်သွင်းပါ။
[vars]
# ဤနေရာတွင် သင်အလိုရှိသော လုံခြုံသော Password ကို ထည့်ပါ။
ADMIN_SECRET = "232003" 

# [[kv_namespaces]] တွင် KV Storage ကို ချိတ်ဆက်ပါ။
[[kv_namespaces]]
binding = "NOTES_KV" # Worker code ထဲမှာ ဒီနာမည်နဲ့ သုံးရပါမယ်။
id = "43345522ebfa461e973e5b576914c08b" 
# ID ကို Cloudflare Dashboard (သို့) `wrangler kv namespace list` မှ ရယူပါ။
